# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNApptentiveExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNApptentiveExample

  target 'RNApptentiveExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNApptentiveExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNApptentiveExample-tvOS

  target 'RNApptentiveExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
